### ISSUE TITLE
ignition command

### ISSUE THREAD

**Issue by SpaceTeddy** [motoz/nbetest#4]
Dear motoz,
I'm using an aduro pellet burner and with your nbetest V13 tool, I can read out a lot of data. So, first of all congrats to that tiny fine tool.
To read out monitor data is a nice thing, but basically I would like to switch the oven on/off via UDP connection. 
Do you have any information, how to start the ignition of that kind of pellet burner?

thanks a lot
chris

**Comment by motoz** [comment]
I have never heard of the aduro burner before, but it obviously has an nbe controller if this program works. A 'standard' nbe V7/13 burner can be shut off with:

    python client.py -p xxxxxxxxxxx set settings/misc/stop 1

and started with

    python client.py -p xxxxxxxxxxx set settings/misc/start 1

The password is required to be able to change settings.

**Comment by SpaceTeddy** [comment]
hi,
unfortunatly it does not work
´´´
python client.py -v -a 192.168.0.38 -s xxxxx -p xxxxxxxxxx get settings/misc/
settings/misc/dl_version=0
settings/misc/shaft_sensor=0
settings/misc/smoke_sensor=1
settings/misc/expansion_module=0
settings/misc/clock_year=15
settings/misc/clock_month=1
settings/misc/clock_date=1
settings/misc/clock_hour=0
settings/misc/clock_minute=0
settings/misc/clock_second=0
settings/misc/clock_changed=0
settings/misc/start=0
settings/misc/stop=0
settings/misc/reset_alarm=0
settings/misc/push_version=0
settings/misc/push_prog_size=0
settings/misc/rsa_key=0
settings/misc/push_picture=0
settings/misc/commit_picture=0
settings/misc/fahrenheit=0
settings/misc/xtea_key=0
settings/misc/dummy=1
settings/misc/wifi_network_status=2
settings/misc/address_registered=0
settings/misc/test=0
settings/misc/url=1
settings/misc/removesensor=0
´´´

´´´
python client.py -v -a 192.168.0.38 -s xxxxx -p xxxxxxxxxx set settings/misc/start 1
Traceback (most recent call last):
  File "client.py", line 81, in <module>
    args.func(args, proxy)
  File "client.py", line 31, in setfunc
    l = proxy.set(args.path, args.value)
  File "/Users/Christian/Downloads/nbetest-testing-v13/protocol.py", line 154, in set
    response = self.make_request(2, '.'.join(d[1:3]) + '=' + value, encrypt=True)
  File "/Users/Christian/Downloads/nbetest-testing-v13/protocol.py", line 174, in make_request
    self.s.sendto(self.request.encode(), self.addr)
  File "/Users/Christian/Downloads/nbetest-testing-v13/frames.py", line 84, in encode
    h = self.public_key.encrypt(h, None)[0]
  File "/usr/local/lib/python2.7/site-packages/Crypto/PublicKey/RSA.py", line 390, in encrypt
    raise NotImplementedError("Use module Crypto.Cipher.PKCS1_OAEP instead")
NotImplementedError: Use module Crypto.Cipher.PKCS1_OAEP instead
´´´
any idea?

...start=1 returns:
```
python client.py -v -a 192.168.0.38 -s xxxxx -p xxxxxxxxxx set settings/misc/start=1
0
```

**Comment by motoz** [comment]
Looks like the crypto library you are using is notcompatible with what I was using. I'm on linux (ubuntu and raspbian) so I just 'apt install python-crypto', but that library seem to have been removed from pip. You are likely using pycryptodome insted, since I get that same error when I try to use that one. Not sure how to solve it, but it could probably work if it's solved, looks like the aduro stove really is just an nbe pellet burner in disguise.

**Comment by SpaceTeddy** [comment]
Yeah, you are right. I‘m on MacOsx and using pycryptodrome via pip. Anyhow, I have some raspberry‘s in my network and try it on Linux. 
My oven is a Aduro H2. It is a hybrid stove and can burn both pellets and wood. Really nice thing. My goal is to include it in my home system.

Thanks a lot for your quick help! Great!

**Comment by motoz** [comment]
Found some pointers here... I'll see if I have time to look at it later: https://stackoverflow.com/questions/44427934/notimplementederror-use-module-crypto-cipher-pkcs1-oaep-instead-error

The stove does look nice, great that they use the same protocol so it still is possible to not give up all control to the cloud... Pellmon could work with it too then, then you could possibly use pellmonMQTT to integrate it with a home automation system.

**Comment by SpaceTeddy** [comment]
alright, I tried your client tool with an raspberry and apt-get python-crypto and it works really nice. So I can start and stop the device.
Really nice! 
to get your tool running with MacOS, i had to install pip install pycrypto library.

**Comment by motoz** [comment]
Great, I read something about 'pycrypto' being deprecated, but it apparently still is available on pip. I added a not the the readme about that.

**Comment by SpaceTeddy** [comment]
one additional information regarding my stove.
The get functions:
``
sw_versions & info
``
does not operate properly, because I get the following payload size error back:
``
python client.py -v -a 192.168.0.38 -s xxxxx -p xxxxxxxxxx get info
``
`` 
Illegal payload size
``

**Comment by motoz** [comment]
Well, the protocol is probably just mostly similar to the pellet burners. The 'root' is coded like this in the code:

    root = ('settings', 'operating_data', 'advanced_data', 'consumption_data', 'event_log','sw_versions','info')

    settings = ('boiler', 'hot_water', 'regulation', 'weather', 'weather2', 'oxygen', 'cleaning', 'hopper', 'fan', 'auger', 'ignition', 'pump', 
        'sun', 'vacuum', 'misc', 'alarm', 'manual')

You can query e.g. settings/boiler/* and get everything below that. but there is unfortunately no way to query settings/* or /*, these levels have to be hardcoded in the client application.

There might not even be something called 'sw_versions' or 'info' in the protocol used in the pellet stove. There might also be more 'root menus' that one just would have to know. You could use wireshark to try to get some insight togheter with the official app or ask for some info from stokersoft.

**Comment by SpaceTeddy** [comment]
Hi,
for the Aduro H2 I found some additional commands, which the Aduro App is using:

``
python ./Downloads/nbetest-testing-v13/client.py -a apprelay2.stokercloud.dk -s xxxxx -p xxxxxxxxx raw 1 wifi.*
``
result:
``
router=0
alive=0
networklist=0
wireless=
``
i.E. for router:
python ./Downloads/nbetest-testing-v13/client.py -a apprelay2.stokercloud.dk -s xxxxx -p xxxxxxxxxx raw 1 wifi.router
``
router=UPC716xxxxx,2,0,1,192.168.0.9,192.168.0.1,-73,0,0,80:7d:3a:xx:xx:xx
``

**Comment by motoz** [comment]
That's good to know, I wouldn't be surprised if the same works for the standard V13 pellet controller.

**Comment by Mahamoti** [comment]
Some tips(For my Aduro H1)

- In my case i had to use python3 (And also install pip + pcrypto there)
`python3 -m pip install pycrypto`
- This did **NOT** work: 
`python3 client.py -v -a ****IP**** -s ***Serial**** -p *****PASS***** set settings/misc/start=1`
- This **did** work :-)
`python3 client.py -v -a ****IP**** -s ***Serial**** -p *****PASS***** set settings/misc/start 1`
The difference is in `start=1` and `start 1`

And you can also use the Aduro cloud with this command:
`python3 client.py -v -a apprelay20.stokercloud.dk -s ***Serial**** -p *****PASS***** set settings/misc/start=1`

**Comment by Mahamoti** [comment]
@SpaceTeddy & @motoz 
Do you happen to know how to change the heat setting on the Aduro H1?
After start-up I would like to put it from heating position III to position I.

**Comment by Mahamoti** [comment]
Ah, i founded:
Heating postion 1: 
`set settings/regulation/fixed_power 10`
Heating postion 2: 
`set settings/regulation/fixed_power 50`
Heating postion 3: 
`set settings/regulation/fixed_power 100`

**Comment by SpaceTeddy** [comment]
yes, correct! 

also interesting for you could be: 
... raw 1 wifi.router
... raw 11 001*

last command use the Aduro App to get the operating_data values. With one command, you can receive many data. Unfortunately you have to sort it. ;)
